### ISSUE TITLE
curly braces connote objects 

### ISSUE THREAD

**Issue by PhillipSenn** [daccfml/cfscript#6]
I think 

    fileUpload({destination},{filefield},{accept},{nameconflict}); 

should be written as

    fileUpload(destination,filefield,accept,nameconflict);

because including the curly brackets connotes that they are objects. I'm using Railo, and Railo is expecting strings.

example:

    fileUpload(getTempDirectory(),form.myFieldname,'','overwrite');

**Comment by atuttle** [comment]
I don't completely agree that `{}` indicates an object, but I do agree that the current formatting is inconsistent with the rest of the document, so I'll fix it...

**Comment by daccfml** [comment]
FWIW, I agree with you on both counts, Adam. Cheers.
